// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   datasource: {
//     url: "postgresql://postgres.pnnpuvdljpugugzzqhyi:KSAVEapp%40123@aws-1-ap-south-1.pooler.supabase.com:5432/postgres",
//     shadowDatabaseUrl: "postgresql://postgres.pnnpuvdljpugugzzqhyi:KSAVEapp%40123@aws-1-ap-south-1.pooler.supabase.com:6543/postgres",

//   },
//   migrations: {
//     path: "prisma/migrations",
//   },
// });
